### ISSUE TITLE
Make two PCBs with TTL parts

### ISSUE THREAD

**Issue by Partins** [kottz/D7039E#28]
For two teams to be able to work independently we need two PCBs of the Tri-state buffer.
Solder them and close this issue

**Comment by Partins** [comment]
Is this finished?

**Comment by mnsnor** [comment]
It has not been tested yet, but it’s all put together Sent from Mail for Windows 10 From: PartinsSent: den 6 oktober 2020 18:26To: kottz/D7039ECc: mnsnor; AssignSubject: Re: [kottz/D7039E] Make two PCBs with TTL parts (#28) Is this finished?—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mnsnor** [comment]
The two PCB's has been made and tested
